config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('tunza_v2.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    # Patient management
    url(r'^patients/', include("register.urls", namespace="patients")),
    url(r'^reminders/', include("reminder.urls", namespace="reminders")),
    url(r'^services/', include("services.urls", namespace="services")),
    url(r'^call_engine/', include("call_engine.urls", namespace="calls")),
    url(r'^reports/', include("reports.urls", namespace="reports")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

register/urls.py
from django.conf.urls import url
from register import views

urlpatterns = [
	url(r'^list/', views.list, name='list'),
	url(r'^(?P<id>\d+)/$', views.profile, name='profile'),

    # Patient manipulations
	url(r'^(?P<id>\d+)/edit/$', views.update, name='update'),
	url(r'^(?P<id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^create/', views.create, name='create'),
    url(r'^discharge/$', views.discharge, name='discharge')
]

tunza_v2/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

register/models.py
from __future__ import unicode_literals
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.urlresolvers import reverse
import uuid
import datetime


class Patient(models.Model):
    anc_number = models.SlugField(max_length=6)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    creation_date = models.DateField(auto_now=True)
    patient_contact = PhoneNumberField(max_length=13, unique=True,
                                       help_text="Enter number in this format +2547209XXXXX")
    patient_name = models.CharField(max_length=64)
    national_id = models.BigIntegerField(default=None, unique=True)
    last_menstrual_date = models.DateField()

    class Meta:
        verbose_name_plural = 'Patients'

    def __unicode__(self):
        return '%s' % self.patient_name

    def last_menstrual(self):
        today = datetime.date.today()
        last_menstrual_date = self.last_menstrual_date
        if last_menstrual_date > today:
            raise ValueError
        else:
            return last_menstrual_date

    def get_absolute_url(self):
        return reverse("patients:profile", kwargs={"id": self.id})


class Discharge(models.Model):
    patient = models.ForeignKey(Patient)
    discharged = models.BooleanField(default=False, verbose_name='Active')
    # discharge_date = models.DateField(blank=True, auto_now=True)

    class Meta:
        verbose_name_plural = 'Discharge'

    def __unicode__(self):
        return '%s' % self.patient.patient_name

tunza_v2/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tunza_v2/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tunza_v2/templates/patients/create.html
{% extends 'users/user_detail.html' %}
{% load crispy_forms_tags %}
{% block panel %}
        <div class="row div_form">
            <div class="col-md-8 col-sm-8" style="color: royalblue; font-size: small">
                <form action='{% url 'patients:create' %}' method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-block">
                        <b>Save</b>
                    </button>
                </form>
            </div>
        </div>
{% endblock %}

tunza_v2/templates/patients/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row"><br>
        <div class="col-md-12 col-sm-12">
            <div class="row">
                <div class="col-md-9 col-sm-9">
                    <form method='GET' action='' role="search">
                        <input type="text" name='q' placeholder="&nbsp;patient&nbsp;"
                               class="control-group inline" value="{{ request.GET.q }}">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-search awesome-space"></i>
                            <b>Search</b>
                        </button>
                    </form>
                </div>
                <div class="col-md-3 col-sm-3">
                    <button class="btn btn-primary btn-sm" style="float: right;">
                        <a href="{% url 'patients:create' %}">
                            <i class="fa fa-plus-circle awesome-space"></i>
                            <b>Add Patient</b>
                        </a>
                    </button>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="CSSTableGenerator">
                        <table>
                            <tr>
                                <td>Patient Name</td>
                                <td>National ID</td>
                                <td>ANC Number</td>
                                <td>Contact</td>
                                <td>Last Menstrual Date</td>
                            </tr>
                            {% for obj in patient_list %}
                                <tr>
                                    <td><a style="color: darkblue;"
                                           href="{{ obj.get_absolute_url }}">{{ obj.patient_name }}</a></td>
                                    <td>{{ obj.national_id }}</td>
                                    <td>{{ obj.anc_number }}</td>
                                    <td>{{ obj.patient_contact }}</td>
                                    <td>{{ obj.last_menstrual }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="pagination">
            <span class="step-links">
                {% if patient_list.has_previous %}
                    <a style="color: darkblue;" href="?page={{ patient_list.previous_page_number }}">
                        <i class="fa fa-chevron-circle-left"></i>
                        <b>previous</b>
                    </a>
                {% endif %}

                <span class="current">
                    <b>Page {{ patient_list.number }} of {{ patient_list.paginator.num_pages }}.</b>
                </span>

                {% if patient_list.has_next %}
                    <a style="color: darkblue;" href="?page={{ patient_list.next_page_number }}">
                        <i class="fa fa-chevron-circle-right"></i>
                        <b>next</b>
                    </a>
                {% endif %}
            </span>
            </div>
        </div>

    </div>
{% endblock content %}

tunza_v2/templates/patients/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ instance_profile.name }}{% endblock %}

{% block content %}
    <div class="row"><br>
    <div class="col-md-4 col-sm-4">
        <div class="row">
            <div class="well">
                <b>Patient Name: </b>{{ instance_profile.patient_name }}<br><br>
                <b>Expected delivery date: </b>{{ instance_edd }}<br><br>
                <b>Discharge Status: </b>{{ instance_profile.discharged }}<br><br>
                {% if instance_profile.discharged %}
                    <b>Discharged on: </b>{{ instance_profile.discharge_date }}<br><br>
                {% endif %}

                <b>Days to Delivery: </b>{{ instance_delivery }}<br><br>
                <button class="btn btn-primary btn-sm">
                    <a href="{% url 'patients:update' id=instance_profile.id %}">Edit</a>
                </button>
                <button class="btn btn-primary btn-sm">
                    <a href="{% url 'patients:delete' id=instance_profile.id %}">Delete</a>
                </button>
                <button class="btn btn-primary btn-sm">
                    <a href="{% url 'patients:list' %}">Patient list</a>
                </button>
            </div>

        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        {% if appointment %}
            <b style="color:lime">Pending Appointments </b><br>
            <ul>
                {% for obj in appointment %}
                    <a href="{{ obj.service.get_absolute_url }}">
                        <b style="color:royalblue">{{ obj.service.service_name }}</b></a>&nbsp;on
                    <b>{{ obj.appointment_date }}</b>&nbsp;
                    to be reminded on&nbsp;{{ obj.date_of_call }}&nbsp;
                    at&nbsp;{{ obj.time_of_call }}<br><br>
                {% endfor %}
            </ul>
        {% else %}
            <b>You have no appointments</b>
        {% endif %}

    </div>
    <div class="col-md-2 col-sm-2">
        <button class="btn btn-primary btn-sm" style="float: right;">
            <a href="{% url 'reminders:create' %}">
                <i class="fa fa-plus-circle"></i>
                <b>Appointment</b>
            </a>
        </button>
    </div>
{% endblock content %}