config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('tunza_v2.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    # Patient management
    url(r'^patients/', include("register.urls", namespace="patients")),
    url(r'^reminders/', include("reminder.urls", namespace="reminders")),
    url(r'^services/', include("services.urls", namespace="services")),
    url(r'^call_engine/', include("call_engine.urls", namespace="calls")),
    url(r'^reports/', include("reports.urls", namespace="reports")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

reminder/urls.py
from django.conf.urls import url
from reminder import views

urlpatterns = [
    # schedule configurations
    url(r'^profile/(?P<id>\d+)/$', views.profile, name='profile'),
    url(r'^create/', views.create, name='create'),
    url(r'^delete/(?P<id>\d+)/delete/$', views.delete, name='delete'),
    url(r'^update/(?P<id>\d+)/edit/$', views.update, name='update'),
    url(r'^list/', views.list, name='list'),
    url(r'^list-tomorrow/$', views.tomorrow, name='tomorrow'),
    url(r'^response/', views.appointment_response, name='response'),
]

tunza_v2/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

reminder/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django import forms
import datetime


# Create your models here.

class Reminder(models.Model):
    patient = models.ForeignKey('register.Patient', on_delete=models.CASCADE,)
    service = models.ForeignKey('services.Service')
    date_created = models.DateField(auto_now = True)
    appointment_date = models.DateField()
    time_of_call = models.TimeField()
    set_on = models.BooleanField(default = True)

    def __unicode__(self):
        return '%s' % self.patient

    def appointment_status(self):
        today = datetime.date.today()
        appointment_date = self.appointment_date
        response = self.response
        if today < appointment_date:
            response = True
        else:
            response = False
        return response

    def date_of_call(self):
        difference = datetime.timedelta(days=1)
        appointment_date = self.appointment_date
        call_date = appointment_date - difference
        return call_date

    def get_absolute_url(self):
        return reverse("reminders:profile", kwargs={"id": self.id})

    class Meta:
        verbose_name_plural = 'Reminders'


class Appointment_Response(models.Model):
    patient = models.ForeignKey(Reminder)
    response_date = models.DateField()
    state = models.BooleanField(default=False)

    def get_patient(self):
        got_patient = self.reminder.patient_id
        return got_patient

    def get_absolute_url(self):
        return reverse("reminders:response", kwargs={"id": self.id})

tunza_v2/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

reminder/forms.py
from django import forms
from .models import Reminder, Appointment_Response


class ReminderForm(forms.ModelForm):
    appointment_date = forms.DateField(label="Date of Reminder", required=True,
                                    widget=forms.DateInput(format='%y-%m-%d',
                                                           attrs={'type': 'date',}))
    time_of_call = forms.TimeField(label="Time of Call", required=True,
                                    widget=forms.TimeInput(format='%H:%M',
                                                           attrs={'type': 'time',}))

    class Meta:
        model = Reminder
        fields = [
            'patient',
            'service',
            'appointment_date',
            'time_of_call',
            'set_on'
        ]

class AppointmentResponseForm(forms.ModelForm):
    state = forms.BooleanField(label="Response Status")
    response_date = forms.DateField(label="Attendance Date", required=True,
                                    widget=forms.DateInput(format=('%y-%m-%d'),
                                                           attrs={'type': 'date',}))

    class Meta:
        model = Appointment_Response
        fields = [
            'patient',
            'response_date',
            'state'
        ]

reminder/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Reminder, Appointment_Response
from .forms import ReminderForm, AppointmentResponseForm
import datetime

gestational_period = datetime.timedelta(days=280)


def profile(request, id=None):
    if not request.user.is_authenticated():
        return render(request, '404.html')
    instance_profile = get_object_or_404(Reminder, id=id)
    rem_date_filter = instance_profile.appointment_date
    today = datetime.datetime.today()
    rem_date = rem_date_filter - datetime.timedelta(days=1)
    # days_rem = rem_date - today
    context = {
        'instance_profile': instance_profile,
        # 'days_rem': days_rem,
        'rem_date': rem_date,
    }
    return render(request, 'reminders/profile.html', context)


def appointment_response(request):
    if not request.user.is_authenticated():
        return render(request, '404.html')
    form = AppointmentResponseForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('/users/')
            # messages.success(request, 'Successfully Created')
    context = {'form': form}
    return render(request, 'reminders/response.html', context)


def create(request):
    '''
    This view creates a new schedule. It captures the patient id, links
    the id to a scheduled objects and passes it to count down. Creates a
    new patient schedule or reminder. It also starts counting down to the
    1 day to reminder date
    '''
    if not request.user.is_authenticated():
        return render(request, '404.html')
    form = ReminderForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Appointment Successfully Created')
            return HttpResponseRedirect('/reminders/list/')
    context = {'form': form,}
    return render(request, 'reminders/create.html', context)


def update(request, id=None):
    if not request.user.is_authenticated():
        return render(request, '404.html')
    instance_profile = get_object_or_404(Reminder, id=id)
    form = ReminderForm(request.POST or None, instance=instance_profile)
    if form.is_valid():
        instance = form.update(commit=False)
        instance.update()
        # messages.success(request, 'Appointment Successfully Updated')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'instance_profile': instance_profile,
        'form': form,
    }
    return render(request, 'reminders/create.html', context)


def delete(request, id=None):
    '''
    This method removes a previously set reminder
    '''
    if not request.user.is_authenticated():
        return render(request, '404.html')
    instance_profile = get_object_or_404(Reminder, id=id)
    instance_profile.delete()
    messages.success(request, 'Appointment Successfully Deleted')
    return redirect('reminders:list')


def list(request):
    '''
    This method counts all the active and discharged reminders specific
    to an expectant mother and returns a list of them
    '''
    if not request.user.is_authenticated():
        return render(request, '404.html')
    reminder_count = Reminder.objects.count()
    queryset_list = Reminder.objects.all().filter(set_on=True).order_by('appointment_date', 'time_of_call',
                                                                        'patient__patient_name')
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(patient__patient_name__icontains=query) |
            Q(service__service_name__icontains=query)
        )
    paginator = Paginator(queryset_list, 8)
    page = request.GET.get('page')
    try:
        reminder_list = paginator.page(page)
    except PageNotAnInteger:
        reminder_list = paginator.page(1)
    except EmptyPage:
        reminder_list = paginator.page(paginator.num_pages)

    context = {
        'reminder_list': reminder_list,
        'reminder_count': reminder_count,
    }
    return render(request, 'reminders/list.html', context)


def response(request):
    if not request.user.is_authenticated():
        return render(request, '404.html')
    form = AppointmentResponseForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Attendance Confirmed')
            return redirect('users:detail')


def tomorrow(request):
    '''
    This function retrieves all the reminders that are due tomorrow and returns
    the list to the user detail (admin) page.
    '''
    difference = datetime.timedelta(days=1)
    today = datetime.date.today()
    call_day = today + difference
    reminder_service = Reminder.objects.values_list('service_id', 'patient_id',
                                                    'service__service_url', 'patient__patient_contact')
    queryset = Reminder.objects.all()
    tomorrow_list = queryset.filter(
        appointment_date=call_day).order_by('time_of_call')
    tomorrow_count = tomorrow_list.count()
    query = request.GET.get('q')
    if query:
        tomorrow_list = tomorrow_list.filter(
            Q(patient__patient_name=query)
        )
    paginator = Paginator(tomorrow_list, 6)
    page = request.GET.get('page')
    try:
        tomorrow_list = paginator.page(page)
    except PageNotAnInteger:
        tomorrow_list = paginator.page(1)
    except EmptyPage:
        tomorrow_list = paginator.page(paginator.num_pages)
    # contact_list = tomorrow_list.filter(patient__patient_contact=)
    context = {
        'tomorrow_list': tomorrow_list,
        'tomorrow_count': tomorrow_count,
        'reminder_service': reminder_service,
        'queryset': queryset,
    }
    return render(request, 'reminders/incoming.html', context)

tunza_v2/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tunza_v2/templates/reminders/create.html
{% extends 'users/user_detail.html' %}
{% load crispy_forms_tags %}
{% block panel %}
    <div class="row">
        <div class="col-md-8 col-sm-8" style="color: royalblue">
            <form action='{% url 'reminders:create' %}' method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                {{ form.reminderDate.label_tag }} {{ form.reminderDate }}
                <button type="submit" class="btn btn-primary btn-block">
                    <b>Save</b>
                </button>
            </form>
        </div>
    </div>
{% endblock %}

tunza_v2/templates/reminders/incoming.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row"><br>
        <div class="col-md-12 col-sm-12">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <form method='GET' action='' role="search">
                        <input type="text" name='q' placeholder=" Patient or Service "
                               class="control-group inline" value="{{ request.GET.q }}">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-search awesome-space"></i>
                            <b>Search</b>
                        </button>
                    </form>
                </div>
                <div class="col-md-6">
                    <b>Schedules due tomorrow:</b>&nbsp;{{ tomorrow_count }} patients
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="CSSTableGenerator">
                        <table>
                            <tr>
                                <td>Patient</td>
                                <td>Service</td>
                                <td>Contact</td>
                            </tr>
                            {% for obj in tomorrow_list %}
                                <tr>
                                    <td>{{ obj.patient }}</td>
                                    <td>{{ obj.service.service_name }}</td>
                                    <td>{{ obj.patient.patient_contact }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="pagination">
                Total Schedule Entries:<b class="awesome-space">{{ tomorrow_count }}</b>
                        <span class="step-links">
                            {% if tomorrow_list.has_previous %}
                                <b><a href="?page={{ tomorrow_list.previous_page_number }}">previous</a></b>
                            {% endif %}

                            <span class="current">
                                <b>Page {{ tomorrow_list.number }} of {{ tomorrow_list.paginator.num_pages }}.</b>
                            </span>

                            {% if tomorrow_list.has_next %}
                                <b> <a href="?page={{ tomorrow_list.next_page_number }}">next</a></b>
                            {% endif %}
                        </span>
            </div>
            {#        {% for obj in reminder_service %}#}
            {#            {{ obj }}<br>#}
            {#        {% endfor %}#}
        </div>
    </div>
{% endblock content %}

tunza_v2/templates/reminders/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row"><br>
        <div class="col-md-12 col-sm-12">
            <div class="row">
                <div class="col-md-9 col-sm-9">
                    <form method='GET' action='' role="search">
                        <input type="text" name='q' placeholder=" Patient or Service "
                               class="control-group inline" value="{{ request.GET.q }}">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-search awesome-space"></i>
                            <b>Search</b>
                        </button>
                    </form>
                </div>
                <div class="col-md-3 col-sm-3">
                    <button class="btn btn-primary btn-sm" style="float: right;">
                        <a href="{% url 'reminders:create' %}">
                            <i class="fa fa-plus-circle awesome-space"></i>
                            <b>Book Appointment</b>
                        </a>
                    </button>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="CSSTableGenerator">
                        <table>
                            <tr>
                                <td>Appointment Date</td>
                                <td>Date of call</td>
                                <td>Time of Call</td>
                                <td>Patient</td>
                                <td>Service</td>
                                <td>Contact</td>
                                <td>Created on</td>
                            </tr>
                            {% for obj in reminder_list %}
                                <tr>
                                    <td><a style="color: darkblue;" href="{{ obj.get_absolute_url }}">
                                        {{ obj.appointment_date }}
                                    </a>
                                    </td>
                                    <td>{{ obj.date_of_call }}</td>
                                    <td>{{ obj.time_of_call }}</td>
                                    <td><a style="color: darkblue;" href="{{ obj.patient.get_absolute_url }}">
                                        {{ obj.patient }}
                                    </a>
                                    </td>
                                    <td>{{ obj.service.service_name }}</td>
                                    <td>{{ obj.patient.patient_contact }}</td>
                                    <td>{{ obj.date_created }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="pagination">
            <span class="step-links">
                {% if reminder_list.has_previous %}
                    <a style="color: darkblue;"
                       href="?page={{ reminder_list.previous_page_number }}">
                        <i class="fa fa-chevron-circle-left"></i>
                        <b>previous</b>
                    </a>
                {% endif %}

                <span class="current">
                    <b>Page {{ reminder_list.number }} of {{ reminder_list.paginator.num_pages }}.</b>
                </span>

                {% if reminder_list.has_next %}
                    <a style="color: darkblue;" href="?page={{ reminder_list.next_page_number }}">
                        <i class="fa fa-chevron-circle-right"></i>
                        <b>next</b>
                    </a>
                {% endif %}
            </span>
            </div>
        </div>

    </div>
{% endblock content %}

tunza_v2/templates/reminders/profile.html
{% extends "users/user_detail.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ reminders }}{% endblock %}

{% block content %}
    <div class="row div_form">
        <div class="col-md-4 col-sm-4" style="color: royalblue;">
            <br>
            <b>Patient Name: </b>{{ instance_profile.patient }}<br><br>
            <b>Appointment date: </b>
            {{ instance_profile.appointment_date }}
            <br><br>
            <b>Service: </b>{{ instance_profile.service }}<br><br>
            <button class="btn btn-primary btn-sm">
                <a href="{% url 'reminders:update' id=instance_profile.id %}">
                    Edit
                </a>
            </button>
            <button class="btn btn-primary btn-sm">
                <a href="{% url 'reminders:delete' id=instance_profile.id %}">
                    Delete
                </a>
            </button>
            <button class="btn btn-primary btn-sm">
                <a href="{% url 'reminders:list' %}">
                    Reminder list
                </a>
            </button>
            <br><br>
            {% block response %}
            {% endblock %}
        </div>
    </div>

{% endblock content %}

tunza_v2/templates/reminders/response.html
{% extends 'users/user_detail.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block admin %}
{% endblock %}
{% block panel %}
    <div class="row div_form">
        <div class="col-md-8 col-sm-8" style="color: royalblue; font-size: small;">
            <form action="{% url 'reminders:response' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-sm">
                    <b>Save Response</b>
                </button>
            </form>
        </div>
    </div>
{% endblock %}