config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('tunza_v2.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    # Patient management
    url(r'^patients/', include("register.urls", namespace="patients")),
    url(r'^reminders/', include("reminder.urls", namespace="reminders")),
    url(r'^services/', include("services.urls", namespace="services")),
    url(r'^call_engine/', include("call_engine.urls", namespace="calls")),
    url(r'^reports/', include("reports.urls", namespace="reports")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

register/urls.py
from django.conf.urls import url
from register import views

urlpatterns = [
	url(r'^list/', views.list, name='list'),
	url(r'^(?P<id>\d+)/$', views.profile, name='profile'),

    # Patient manipulations
	url(r'^(?P<id>\d+)/edit/$', views.update, name='update'),
	url(r'^(?P<id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^create/', views.create, name='create'),
    url(r'^discharge/$', views.discharge, name='discharge')
]

reminder/urls.py
from django.conf.urls import url
from reminder import views

urlpatterns = [
    # schedule configurations
    url(r'^profile/(?P<id>\d+)/$', views.profile, name='profile'),
    url(r'^create/', views.create, name='create'),
    url(r'^delete/(?P<id>\d+)/delete/$', views.delete, name='delete'),
    url(r'^update/(?P<id>\d+)/edit/$', views.update, name='update'),
    url(r'^list/', views.list, name='list'),
    url(r'^list-tomorrow/$', views.tomorrow, name='tomorrow'),
    url(r'^response/', views.appointment_response, name='response'),
]

reports/urls.py
from django.conf.urls import url, patterns
from reports import views

urlpatterns=[
    url(r'^appointment_report/$', views.AppointmentReports, name='appointment_report'),
    url(r'^call_report/$', views.CallReports, name='call_report'),
    url(r'^patient_report/$', views.PatientReports, name='patient_report'),
    url(r'^reminder_report/$', views.AppointmentResponseReports, name='response_report'),
    url(r'^service_report/$', views.ServiceReports, name='service_report'),
]

tunza_v2/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tunza_v2/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tunza_v2/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tunza_v2/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block cs %}
{% endblock %}

{% block content %}
    <div class="row"><br>
        <div class="col-md-3 col-sm-3">
            {% if object.name %}
                <h3><p>Welcome {{ object.name }}</p></h3>
            {% endif %}

            {% block admin %}
                {% if object == request.user %}
                    <!-- Action buttons -->
                    <div class="row">
                        <div class="col-md-12 col-sm-12 ">
                            <a class="btn btn-primary btn-block" href="{% url 'reminders:response' %}">
                                <b>Confirm Appointment</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'patients:discharge' %}">
                                <b>Discharge Patient</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'services:create' %}">
                                <b>Create Service</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'reminders:tomorrow' %}">
                                <b>Immediate Appointments</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'reports:response_report' %}">
                                <b>Call Reports</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'reports:patient_report' %}">
                                <b>Patient Reports</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'reports:appointment_report' %}">
                                <b>Appointment Reports</b>
                            </a>
                            <a class="btn btn-primary btn-block" href="{% url 'reports:service_report' %}">
                                <b>Service Reports</b>
                            </a>
                        </div>
                    </div>
                    <!-- End Action buttons -->
                {% endif %}
            {% endblock %}
        </div>
        <div class="col-sm-9">
            <div class="well">
                <h2>{{ object.username }}</h2>
            </div>
            {% block panel %}
            {% endblock %}
        </div>
    </div>
{% endblock content %}

{% block js %}
{% endblock %}

tunza_v2/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

tunza_v2/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}